### ISSUE TITLE
How to use complex query in X-Ldap-Template?

### ISSUE THREAD

**Issue by strannick-ru** [nginxinc/nginx-ldap-auth#16]
Hello!

I need to check username and group of user.
Try to use this:
proxy_set_header X-Ldap-Template "(&(SAMAccountName=%(username))(memberof=CN=MyGroup,OU=Groups,DC=example,DC=local))"";
but it not works.

How write my query right way?

**Comment by DerfOh** [comment]
I'm looking to do something similar. A way to define an ACL for specific AD groups would make this the perfect solution for me.

**Comment by arozyev** [comment]
Perhaps you forgot "s" after %(username), it should be "%(username)s".

**Comment by vl-homutov** [comment]
Please do not create issues just to discuss related topics.
