### ISSUE TITLE
Undocumented Group Restriction Values

### ISSUE THREAD

**Issue by DerfOh** [nginxinc/nginx-ldap-auth#17]
This is in reference to #16 

It seems that there are a number of undocumented values that would be nice to have provided in README.md

Namely restriction types like:
```
auth_ldap_require group 'cn=admins,ou=group,dc=example,dc=com';
auth_ldap_require group 'ou=HR,dc=example,dc=com';
auth_ldap_satisfy all;
```

**Comment by vl-homutov** [comment]
You are referring to some 3rd-party ldap authentication module, and not nginx-ldap-auth.
