### ISSUE TITLE
How to authenticate before sending proxy to smtp server

### ISSUE THREAD

**Issue by vivek779** [nginxinc/nginx-ldap-auth#2]
hello i was working nginx .i want to I was working on nginx webserver .I want to authenticate with user name and password just before it send proxy to smtp server is it possible with this nginx-ldap-auth module could anyone please guide me and provide me an eg.

**Comment by vl-homutov** [comment]
This example solution is designed to work with http-auth-request module, and does not work with mail proxy. However, you may want to look at http://nginx.org/en/docs/mail/ngx_mail_auth_http_module.html
and authenticate using similar approach.

Please do not create issue on github to just ask question. You may ask questions here: https://www.nginx.com/blog/nginx-plus-authenticate-users/
