### ISSUE TITLE
dead link in README.md

### ISSUE THREAD

**Issue by yannw** [nginxinc/nginx-ldap-auth#20]
Hello, 
minor issue:
The NGINX LDAP Architecture graphic in README.md is missing: 
[NGINX LDAP Architecture](http://nginx.wpengine.com/wp-content/uploads/2015/06/components-e1434577427617.jpg) -> 404

Thanks, 
best regards, 
yann

**Comment by oxpa** [comment]
Thank you for feedback. I'll fix the link.
