### ISSUE TITLE
proxy_set_header X-Ldap-Opt-Referals

### ISSUE THREAD

**Issue by posledov** [nginxinc/nginx-ldap-auth#21]
Hello.

It would be great to be able to specify the OPT_REFERRAL option with the related header.

This is useful in case of:
1. when updating with git (there is no need to edit the script)
2. when working with multiple independent LDAP servers

**Comment by vl-homutov** [comment]
The intention for the current nginx-ldap-auth code is to be example/reference implementation, showing how LDAP integration can be done in principle. There are numerous extensions and improvements that may be invented on top of this, but we'd like to keep original code simple. 
Use case with multiple LDAP servers is out of example scope.
