### ISSUE TITLE
nginx: [emerg] "events" directive is not allowed 

### ISSUE THREAD

**Issue by hadar0x** [nginxinc/nginx-ldap-auth#22]
I'm using the default configuration file, and when running nginx -t I get the following error:
```
nginx: [emerg] "events" directive is not allowed here in /etc/nginx/conf.d/nginx-ldap-auth.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed

```

**Comment by oxpa** [comment]
Provided configuration is an example only. It contains full nginx configuration and is not intended to be used out of the box as an included file..

**Comment by hatdropper1977** [comment]
Move /etc/nginx/conf.d/nginx-ldap-auth.conf to /etc/nginx/nginx.conf.
