### ISSUE TITLE
proxy_set_header X-Ldap-Template in README.md

### ISSUE THREAD

**Issue by Tolivier** [nginxinc/nginx-ldap-auth#37]
IT's indicated that the template X-Ldap-Template could be:
"(&(cn=%(username)s)(memberOf=cn=group1,cn=Users,dc=example,dc=com))";
It's:
"(&(cn=%(username)s)(memberOf=cn=group1,cn=**Groups**,dc=example,dc=com))";

**Comment by vl-homutov** [comment]
It's just an example, I see no contradiction that there is a group under Users entry.
