### ISSUE TITLE
cookies timeout [feature]

### ISSUE THREAD

**Issue by doomzhou** [nginxinc/nginx-ldap-auth#4]
i write cookies timeout code

    expiretime = datetime.now() + timedelta(minutes=1)
    enc = base64.b64encode(user + ':' + passwd)
    self.send_header('Set-Cookie', 'nginxauth=' + enc + '; httponly; Expires=%s' % expiretime.strftime('%d-%b-%y %H:%M:%S'))

but not working, any suggest?

**Comment by vl-homutov** [comment]
Please do not use issue tracker to ask questions. If you want to add a feature, you may develop it and create pull request.
