### ISSUE TITLE
LDAP connection always has user/password pair. For the anonymous access, use 'anonymous' login with empty password, if your server is configured to allow it.

### ISSUE THREAD

**Issue by alnhk** [nginxinc/nginx-ldap-auth#53]
_Originally posted by @vl-homutov in https://github.com/nginxinc/nginx-ldap-auth/issues/52#issuecomment-422722501_

There is no "anonymous user." The LDAP server supports anonymous bind, which means you don't bind as a user. Most software allows you to supply empty strings for DN and password to do this.
https://ldap.com/the-ldap-bind-operation/

I am only providing this :
url ldap://nsp-openldap-local:389;
 binddn ou=people,dc=odc,dc=im;
 binddn_passwd  ;
 require valid_user;

**Comment by vl-homutov** [comment]
So what is the problem when you provide empty DN/password?

**Comment by vl-homutov** [comment]
Feedback timeout.
