### ISSUE TITLE
Python 2 Deprecation

### ISSUE THREAD

**Issue by mhofer117** [nginxinc/nginx-ldap-auth#60]
When  building the container, PIP will warn about Python 2 deprecation:

``DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.``

It is probably a good idea to start migrating the script(s) to python3 for future compatibility.

[python deprecation countdown](https://pythonclock.org/)

**Comment by alexizmailov** [comment]
Hi. I'm stuck with python 2 as well and a simple change of docker image from `python:2` to `python:3` didn't work, obviously.
So thumb up for migrating this to Python 3.

**Comment by goochjj** [comment]
See PR #66

**Comment by vl-homutov** [comment]
Thank you for the remind, python 3 is obviously the thing that needs to be done.

**Comment by speculatrix** [comment]
actually, I think the first step is to get the pylint score up from just over 2 to over 9, the script is  pretty fugly.

**Comment by ptoews** [comment]
Anything new about this? There are only 2 months until Python 2 End-of-Life.

**Comment by vl-homutov** [comment]
Not yet. The plan is to make last release with python2, and switch to v3 without attempts to support both. I've put tests into docker, so testing will be a bit easier. Stay tuned.

25 октября 2019 г. 19:41:32 GMT+03:00, Philipp <notifications@github.com> пишет:
>Anything new about this? There are only 2 months until Python 2
>End-of-Life.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nginxinc/nginx-ldap-auth/issues/60#issuecomment-546426146

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by vl-homutov** [comment]
Merged and updated python3 support.
