### ISSUE TITLE
Unable to push logs of py daemon to a separate file

### ISSUE THREAD

**Issue by rajdeep2001** [nginxinc/nginx-ldap-auth#97]
We are running this module on Nginx Plus AMI EC2 instance i.e. no containerisation. Nginx conf is fine. However, unable to push logs to a separate file and have that propagated to Cloudwatch. $LOG env var is not working OR please suggest how to set $LOG var to push the standard output and error logs to a different file. Updating the documentation with LOG setup would be really useful. Much appreciated!!

Py daemon has been setup as a systemd unit.
**systemd v219**

**Unit file:**
```
[Unit]
Description=LDAP authentication helper daemon for Nginx.
Documentation=https://github.com/nginxinc/nginx-ldap-auth
After=network.target network-online.target

[Service]
Type=simple
Environment="LOG=/var/log/nginx/ldap_auth_daemon.log"         # does not work
ExecStart=/bin/python3 /etc/nginx-ldap/nginx-ldap-auth-daemon.py
StandardOutput=append:/var/log/nginx/ldap_auth_daemon.log  # does not work probably bcoz of systemd version.
StandardError=append:/var/log/nginx/ldap_auth_daemon.log.    # does not work probably bcoz of systemd version.
KillMode=process
KillSignal=SIGINT
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
**nginx-ldap-auth.default**
```
# these are used with systemd too
# so please keep options names inside variables

LOG=/var/log/nginx/ldap_auth_daemon.log                  # does not work.
```

**Comment by tippexs** [comment]
What OS are you using? The ideal way to forward stdout to a file using systemd is the way you already explained above. Another one is to redirect to log stream to a file using `2>&1 >> /var/log/your.log`.

This will append the `stdout` as well as the `stderr` to a custom logfile.

**Comment by rajdeep2001** [comment]
Below redirection works:-
ExecStart=/bin/sh -c 'exec /bin/python3 /etc/nginx-ldap/nginx-ldap-auth-daemon.py 2>&1 >> /var/log/nginx/ldap_auth_daemon.log'

However, the service/process writes to the above redirected log file only when the systemd service is stopped. While it is in the **running** state, it does not write to the log file.

**Comment by rajdeep2001** [comment]
Sorry for the delay, this issue is fixed, was a buffer issue. Can be closed. Thank👍
